Add ZZZ gacha support + fix for Chronicled Banner
seriaati/genshin.py pull request #206
Opened 2024-07-09 02:36 UTC by FuriaPaladins

# About this PR
This PR adds support for Zenless Zone Zero's gacha (Signal Searches). It also fixes an issue with Genshin's gacha and not parsing wishes on the Chronicled Banner.

# Notes
- For ZZZ's gacha, “real_gacha_type” is used in requests. The “gacha_type” values typically start with 200 (e.g., 2001 for standard banner, 2002 for character banner, etc.). However, the Bangboo banner doesn’t return any values for "2005" (the Bangboo banner’s real_gacha_type is 5). I couldn’t figure out the gacha_type value for the banner, but it seems safe to keep the real_gacha_type for now, as Genshin and HSR still parse correctly even with the real_gacha_type parameter included.
- I had to remove banner_name from the Genshin Wish model as the Chronicled banner isn't returned from the "get_banner_names" method (most likely due to the fact that the banner isn't active right now) and I could not parse the banner with banner_name included.

2024-07-09 02:48 UTC, seriaati commented
Is anyone here experienced with the gacha component? I've never used it but uh, looks good to me. Also, this is tested right?

2024-07-09 03:34 UTC, omg-xtao requested changes

2024-07-09 03:34 UTC, omg-xtao commented on genshin/client/routes.py
> +        nap="https://public-operation-nap-sg.hoyoverse.com/common/gacha_record/api/",
```suggestion
        nap="https://public-operation-nap.mihoyo.com/common/gacha_record/api/",
```

2024-07-09 09:47 UTC, FuriaPaladins commented
Yep, I've tested it with all 3 games just in case, and also tested the genshin change with an authkey that had wishes on the chronicled banner

2024-07-10 03:54 UTC, omg-xtao approved these changes

2024-07-10 03:56 UTC, merged