Add More ZZZ Features
seriaati/genshin.py pull request #207
Opened 2024-07-10 11:25 UTC by seriaati

2024-07-10 12:20 UTC, seriaati commented
Only missing Shiyu defense now, I don't have data cuz I'm only level 26 :(

2024-07-10 14:08 UTC, omg-xtao requested changes

2024-07-10 14:08 UTC, omg-xtao commented on genshin/models/zzz/character.py
> +    name: str
```suggestion
    name: str
    icon: str
```

2024-07-11 02:34 UTC, omg-xtao approved these changes

2024-07-11 11:54 UTC, merged