add proxy setting
seriaati/genshin.py pull request #28
Opened 2022-05-13 14:16 UTC by LuckyTain

Some endpoint block some IP address, add a aiohttp proxy setting to client. 

https://docs.aiohttp.org/en/stable/client_advanced.html

Hoyolab(oversea) block Chinese IP, a http proxy can help😀

2022-05-13 14:38 UTC, thesadru commented
This can be done by overwriting the `create_session` method of your cookie manager. I like the idea of making a proxy easier though.

2022-05-13 16:06 UTC, LuckyTain commented
> This can be done by overwriting the `create_session` method of your cookie manager. I like the idea of making a proxy easier though.

I have no idea how to overwriting the `create_session` method to make this work. 
In aiohttp doc, I only found I can set proxy inside session.request(proxy=)

2022-05-13 18:32 UTC, thesadru requested changes
Great idea but I think it could be implemented better. I'm probably gonna try to do this myself anyway.

2022-05-13 18:32 UTC, thesadru commented on genshin/client/components/base.py
> +    _proxy: typing.Optional[typing.Union[pydantic.AnyUrl, str]]
This should ideally be an attribute of the cookie manager

2022-05-13 18:32 UTC, thesadru commented on genshin/client/components/base.py
> +                pydantic.parse_obj_as(pydantic.AnyUrl, proxy)
`yarl.URL` is used instead of `pydantic`'s urls

2022-05-13 18:32 UTC, thesadru commented on genshin/client/components/base.py
> +        self._proxy = proxy if proxy else None
This does practically nothing in terms of validation, probably didn't even need to be a property at that point.

2022-05-13 18:32 UTC, thesadru commented on genshin/client/components/base.py
> +        """Set proxy"""
This should be a comment, not a docstring.

2022-05-14 10:39 UTC, LuckyTain commented
Thank you, I review the code and make some changes, I will open another pull requests

2022-05-14 10:39 UTC, closed without merging

2022-05-14 10:43 UTC, thesadru commented
Why another pull request?

2022-05-14 10:44 UTC, GauravM512 commented
Yes just change your source , it'll change

2022-05-14 10:49 UTC, LuckyTain commented
> Why another pull request? You can just edit the code here, can't you?
Because I create a new branch to rewrite, and I want to keep the old branch.
sorry for my lack knowledge of git